var namesOfMales=["Kwasi","Kwadwo","Kwabena","Kwaku","Yaw","Kofi","Kwame"]
var namesOfFemales=["Akosua","Adwoa","Abenaa","Akua","Yaa","Afua","Ama"]
var yearofbirth=document.getElementById("yearofbirth").value;
var monthofbirth=document.getElementById("monthofbirth").value;
var dateofbirth=document.getElementById("dateofbirth");
var dateformat=new Date(date,month,year);
dateformat.setDate(parseInt(date));
dateformat.setMonth(parseInt(month));
dateformat.setUTCFullYear(parseInt(year));

var dayOfWeek=dateformat.getDay();//the day is generated by being assigned indexes, whereby Sunday is day 0
if (dayOfWeek===0){
    ('Sunday');
} else if (dayOfWeek===1){
    ('Monday');
} else if (dayOfWeek===2){
    ('Tuesday');
} else if (dayOfWeek===3){
    ('Wednesday');
} else if (dayOfWeek===4){
    ('Thursday');
} else if (dayOfWeek===5){
    ('Friday');
} else if (dayOfWeek===6){
    ('Saturday');
}