var namesOfMales=["Kwasi","Kwadwo","Kwabena","Kwaku","Yaw","Kofi","Kwame"]
var namesOfFemales=["Akosua","Adwoa","Abenaa","Akua","Yaa","Afua","Ama"]
var yearofbirth=document.getElementById("yearofbirth").value;
var monthofbirth=document.getElementById("monthofbirth").value;
var dateofbirth=document.getElementById("dateofbirth");
var dateformat=new Date(date,month,year);
dateformat.setDate(parseInt(date));
dateformat.setMonth(parseInt(month));
dateformat.setUTCFullYear(parseInt(year));

var dayOfWeek=dateformat.getDay();//the day is generated by being assigned indexes, whereby Sunday is day 0
if (dayOfWeek===0){
    ('Sunday');
} else if (dayOfWeek===1){
    ('Monday');
} else if (dayOfWeek===2){
    ('Tuesday');
} else if (dayOfWeek===3){
    ('Wednesday');
} else if (dayOfWeek===4){
    ('Thursday');
} else if (dayOfWeek===5){
    ('Friday');
} else if (dayOfWeek===6){
    ('Saturday');
}
if (yearofbirth==NaN||yearofbirth.length!=4||yearofbirth==null){
    alert('Invalid year. Enter at least 4 digits.');
} else if (monthofbirth<1||monthofbirth==NaN||monthofbirth==null||monthofbirth>12){
    alert('Kindly enter a valid month.Eg 06');
} else if(dateofbirth<1||dateofbirth==NaN||dateofbirth==null||dateofbirth>31){
    alert('Kindly enter a valid date. Eg 26');
} else if (document.getElementById('Male').checked==true && document.getElementById('Female').checked==false){
    alert('Your Akan name is'+namesOfMales[dayOfWeek]+'!');
} else if (document.getElementById('Female').checked==true && document.getElementById('Male').checked==false){
    alert('Your Akan name is'+namesOfMales[dayOfWeek]+'!');
}