function check(){
    var namesOfMales=["Kwasi","Kwadwo","Kwabena","Kwaku","Yaw","Kofi","Kwame"]
    var namesOfFemales=["Akosua","Adwoa","Abenaa","Akua","Yaa","Afua","Ama"]

    var yearofbirth=document.getElementById("yearofbirth").value;
    var monthofbirth=document.getElementById("monthofbirth").value;
    var dateofbirth=document.getElementById("dateofbirth");
    var dateformat=new Date(dateofbirth,monthofbirth,yearofbirth);

    dateformat.setDate(parseInt(dateofbirth));
    dateformat.setMonth(parseInt(monthofbirth));
    dateformat.setUTCFullYear(parseInt(yearofbirth));

    var dayOfWeek=dateformat.getDay();//the day is generated by being assigned indexes, whereby Sunday is day 0
    
    if (yearofbirth==NaN||yearofbirth.length!=4||yearofbirth==null){
        alert('Invalid year. Enter at least 4 digits.');
    } else if (monthofbirth<1||monthofbirth==NaN||monthofbirth==null||monthofbirth>12){
        alert('Kindly enter a valid month.Eg 06');
    } else if(dateofbirth<1||dateofbirth==NaN||dateofbirth==null||dateofbirth>31){
        alert('Kindly enter a valid date. Eg 26');
    } else if (document.getElementById('Male').checked==true && document.getElementById('Female').checked==false){
        alert('Your Akan name is'+' '+namesOfMales[dayOfWeek]+'!');
    } else if (document.getElementById('Male').checked==false && document.getElementById('Female').checked==true){
        alert('Your Akan name is'+' '+namesOfFemales[dayOfWeek]+'!');
    }
}